### ISSUE TITLE
Publishing to Pact Broker instead of Pactflow

### ISSUE THREAD

**Issue by suadev** [pactflow/example-consumer-dotnet#15]
Is there a sample repo that demonstrate how to publish pacts to pact broker?  I used to publish pacts using pactnet from right after the consumer tests. It looks like it is not possible with the latest version?

**Comment by YOU54F** [comment]
the capability was removed as part of the upgrade to pact net v4 and migration to the pact rust core backend.

the recommendation is to publish the pact cli tools, and is noted in the pact net upgrade docs in its  repository

**Comment by suadev** [comment]
Thank you @YOU54F

**Comment by suadev** [comment]
Btw, I am using V3 now. Should i use cli tool to publish pacts?

**Comment by suadev** [comment]
Hi @YOU54F 

I want to add as a new stage publishing pacts to pact broker in my CI pipeline. (gitlab preferred)

Is there a reference repo or something that can help me?   

Thanks!

**Comment by YOU54F** [comment]
there is an example of gitlab being used in this repo

https://gitlab.com/YOU54F/example-consumer-dotnet/-/blob/master/.gitlab-ci.yml?ref_type=heads

the cli tools are downloaded with the make deps step

**Comment by suadev** [comment]
That's great. Thanks!
